In [1]:
#importing libraries

import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
ds=pd.read_csv('uncleaned.csv')
ds

,Age,Gender,Previous_Tumor_Size,Time_Since_Diagnosis,Treatment_Type,Stage,Genetic_Risk,Smoking_History,Alcohol_Consumption,BMI,Tumor_Growth_Rate
0,70.0,Female,8.242534,68,Surgery,IV,Low,Yes,Moderate,34.871079,23.142463
1,31.0,Female,NaN,54,Radiotherapy,I,High,Yes,Moderate,19.992288,18.939165
2,44.0,Female,8.176031,79,Surgery,II,Low,No,Low,21.825540,20.383671
3,43.0,Female,2.140415,80,Chemotherapy,IV,High,No,Moderate,26.912637,30.137133
4,47.0,Male,3.311321,67,Radiotherapy,I,Low,Yes,Moderate,23.116841,18.683555
...,...,...,...,...,...,...,...,...,...,...,...
5995,62.0,Female,4.031133,67,Chemotherapy,II,Low,No,Low,24.851126,21.952570
5996,34.0,Male,9.827590,97,Surgery,III,Low,Yes,Low,NaN,26.472124
5997,25.0,Male,7.253101,83,Surgery,II,Low,Yes,High,22.703204,23.482034
5998,26.0,Female,8.767490,85,Radiotherapy,IV,Low,Yes,Moderate,24.722549,26.972971
5999,64.0,Female,6.003208,111,Chemotherapy,IV,High,No,High,27.147790,38.836021

In [3]:
ds.describe()

,Age,Previous_Tumor_Size,Time_Since_Diagnosis,BMI,Tumor_Growth_Rate
count,5764.000000,5761.000000,6000.000000,5765.000000,6000.000000
mean,50.305344,5.522814,60.039833,27.063055,19.127927
std,18.720723,2.589316,34.371851,7.087942,7.765440
min,20.000000,1.001667,1.000000,18.503352,-1.246437
25%,35.000000,3.344657,30.000000,22.629897,12.996469
50%,50.000000,5.551956,60.000000,26.681024,19.054528
75%,65.000000,7.737082,90.000000,30.798121,25.118110
max,150.000000,9.997764,119.000000,100.000000,40.355175

In [3]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   5764 non-null   float64
 1   Gender                6000 non-null   object
 2   Previous_Tumor_Size   5761 non-null   float64
 3   Time_Since_Diagnosis  6000 non-null   int64
 4   Treatment_Type        6000 non-null   object
 5   Stage                 6000 non-null   object
 6   Genetic_Risk          6000 non-null   object
 7   Smoking_History       6000 non-null   object
 8   Alcohol_Consumption   6000 non-null   object
 9   BMI                   5765 non-null   float64
 10  Tumor_Growth_Rate     6000 non-null   float64
dtypes: float64(4), int64(1), object(6)
memory usage: 515.8+ KB

In [4]:
ds.columns

Index(['Age', 'Gender', 'Previous_Tumor_Size', 'Time_Since_Diagnosis',
       'Treatment_Type', 'Stage', 'Genetic_Risk', 'Smoking_History',
       'Alcohol_Consumption', 'BMI', 'Tumor_Growth_Rate'],
      dtype='object')

In [5]:
# Fill missing with median
ds['Age'] = ds['Age'].fillna(ds['Age'].median())

# Remove unrealistic values
ds = ds[(ds['Age'] >= 0) & (ds['Age'] <= 100)]

# Convert to integer
ds['Age'] = ds['Age'].astype(int)