In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
ds = pd.read_csv("cancer_growth.csv")
ds

,Unnamed: 0,Age,Gender,Previous_Tumor_Size,Time_Since_Diagnosis,Stage,Genetic_Risk,Smoking_History,Alcohol_Consumption,BMI,Tumor_Growth_Rate,Treatment_Chemotherapy,Treatment_Radiotherapy,Treatment_Surgery
0,0,70,1,8.242534,68,4,0,1,0.0,34.871079,23.142463,False,False,True
1,1,31,1,5.557241,54,1,2,1,0.0,19.992288,18.939165,False,True,False
2,2,44,1,8.176031,79,2,0,0,0.0,21.825540,20.383671,False,False,True
3,3,43,1,2.140415,80,4,2,0,0.0,26.912637,30.137133,True,False,False
4,4,47,0,3.311321,67,1,0,1,0.0,23.116841,18.683555,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5933,5995,62,1,4.031133,67,2,0,0,0.0,24.851126,21.952570,True,False,False
5934,5996,34,0,9.827590,97,3,0,1,0.0,26.685024,26.472124,False,False,True
5935,5997,25,0,7.253101,83,2,0,1,2.0,22.703204,23.482034,False,False,True
5936,5998,26,1,8.767490,85,4,0,1,0.0,24.722549,26.972971,False,True,False
5937,5999,64,1,6.003208,111,4,2,0,2.0,27.147790,38.836021,True,False,False

In [3]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5938 entries, 0 to 5937
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              5938 non-null   int64
 1   Age                     5938 non-null   int64
 2   Gender                  5938 non-null   int64
 3   Previous_Tumor_Size     5938 non-null   float64
 4   Time_Since_Diagnosis    5938 non-null   int64
 5   Stage                   5938 non-null   int64
 6   Genetic_Risk            5938 non-null   int64
 7   Smoking_History         5938 non-null   int64
 8   Alcohol_Consumption     5938 non-null   float64
 9   BMI                     5938 non-null   float64
 10  Tumor_Growth_Rate       5938 non-null   float64
 11  Treatment_Chemotherapy  5938 non-null   bool
 12  Treatment_Radiotherapy  5938 non-null   bool
 13  Treatment_Surgery       5938 non-null   bool
dtypes: bool(3), float64(4), int64(7)
memory usage: 527.8 KB

In [4]:
ds.columns

Index(['Unnamed: 0', 'Age', 'Gender', 'Previous_Tumor_Size',
       'Time_Since_Diagnosis', 'Stage', 'Genetic_Risk', 'Smoking_History',
       'Alcohol_Consumption', 'BMI', 'Tumor_Growth_Rate',
       'Treatment_Chemotherapy', 'Treatment_Radiotherapy',
       'Treatment_Surgery'],
      dtype='object')

In [5]:
#splitting data into independent and dependent variables

x=ds[['Age', 'Gender', 'Previous_Tumor_Size',
       'Time_Since_Diagnosis', 'Stage', 'Genetic_Risk', 'Smoking_History',
       'Alcohol_Consumption', 'BMI',
       'Treatment_Chemotherapy', 'Treatment_Radiotherapy',
       'Treatment_Surgery']]
y=ds[['Tumor_Growth_Rate']]

In [6]:
x

,Age,Gender,Previous_Tumor_Size,Time_Since_Diagnosis,Stage,Genetic_Risk,Smoking_History,Alcohol_Consumption,BMI,Treatment_Chemotherapy,Treatment_Radiotherapy,Treatment_Surgery
0,70,1,8.242534,68,4,0,1,0.0,34.871079,False,False,True
1,31,1,5.557241,54,1,2,1,0.0,19.992288,False,True,False
2,44,1,8.176031,79,2,0,0,0.0,21.825540,False,False,True
3,43,1,2.140415,80,4,2,0,0.0,26.912637,True,False,False
4,47,0,3.311321,67,1,0,1,0.0,23.116841,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
5933,62,1,4.031133,67,2,0,0,0.0,24.851126,True,False,False
5934,34,0,9.827590,97,3,0,1,0.0,26.685024,False,False,True
5935,25,0,7.253101,83,2,0,1,2.0,22.703204,False,False,True
5936,26,1,8.767490,85,4,0,1,0.0,24.722549,False,True,False
5937,64,1,6.003208,111,4,2,0,2.0,27.147790,True,False,False

In [7]:
y

      Tumor_Growth_Rate
0             23.142463
1             18.939165
2             20.383671
3             30.137133
4             18.683555
...                 ...
5933          21.952570
5934          26.472124
5935          23.482034
5936          26.972971
5937          38.836021

[5938 rows x 1 columns]

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [10]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [11]:
y_pred = model.predict(X_test)

In [13]:
from sklearn.metrics import  r2_score

print("✅ Multiple Linear Regression Results")
print("R² Score:", r2_score(y_test, y_pred))

✅ Multiple Linear Regression Results
R² Score: 0.889342898671133

In [18]:
#user input
print("\nEnter patient details:")

age = int(input("Age: "))
gender = int(input("Gender (Male=0, Female=1): "))
previous_size = float(input("Previous Tumor Size: "))
time_since = int(input("Time Since Diagnosis: "))
stage = int(input("Stage (I=1, II=2, III=3, IV=4): "))
genetic_risk = int(input("Genetic Risk (Low=0, Medium=1, High=2): "))
smoking = int(input("Smoking History (No=0, Yes=1): "))
alcohol = int(input("Alcohol Consumption (Low=0, Medium=1, High=2): "))
bmi = float(input("BMI: "))

# Treatment one-hot encoding (only one should be 1)
treatment_chemo = int(input("Treatment Chemotherapy (Yes=1, No=0): "))
treatment_radio = int(input("Treatment Radiotherapy (Yes=1, No=0): "))
treatment_surgery = int(input("Treatment Surgery (Yes=1, No=0): "))

user_data = pd.DataFrame([[
    age, gender, previous_size, time_since, stage, genetic_risk, smoking,
    alcohol, bmi, treatment_chemo, treatment_radio, treatment_surgery
]], columns=x.columns)

prediction = model.predict(user_data)[0]


print("\n🎯 Predicted Tumor Growth Rate:",prediction)

Enter patient details:

Age:  20
Gender (Male=0, Female=1):  1
Previous Tumor Size:  12
Time Since Diagnosis:  2
Stage (I=1, II=2, III=3, IV=4):  1
Genetic Risk (Low=0, Medium=1, High=2):  1
Smoking History (No=0, Yes=1):  1
Alcohol Consumption (Low=0, Medium=1, High=2):  2
BMI:  12
Treatment Chemotherapy (Yes=1, No=0):  1
Treatment Radiotherapy (Yes=1, No=0):  0
Treatment Surgery (Yes=1, No=0):  0

🎯 Predicted Tumor Growth Rate: [7.47378657]